import React from "react";

const PrivacyPolicy = () => {
  return (
      <div className="space-y-4 md:space-y-8 [&_div]:space-y-4 [&_h3]:text-white [&_h3]:font-semibold">
        <div>
          <h3>
            THIS PRIVACY POLICY IS AN ELECTRONIC RECORD PUBLISHED AND CONSTRUED
            IN ACCORDANCE WITH THE PROVISIONS OF THE INFORMATION TECHNOLOGY ACT,
            2000 AND THE INFORMATION TECHNOLOGY (REASONABLE SECURITY PRACTICES
            AND PROCEDURES AND SENSITIVE PERSONAL DATA OF INFORMATION) RULES,
            2011 AND THE AMENDED PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN
            VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000.
            THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES
            NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
          </h3>
          <p>
            Please read the following Privacy Policy carefully before using or
            registering or uploading or accessing any material, information or
            availing any services on the Company's online platform i.e.,
            www.lightstorm.in and/or mobile app namely “_______” (hereinafter
            collectively referred to as the "Website").For the purposes of this
            Privacy Policy,any reference to “sites” is a reference to any of the
            CompanyWebsite (including any mobile version of such Website),
            whether operated under the banner of the Company or a brand name
            that we own. By accessing and using the Website, you indicate that
            you understand, agree and consent to this Privacy Policy, without
            limitation or qualification. If you do not agree to the terms of
            this Privacy Policy, exit this page and do not access or use the
            Website.
            <br />
            <br />
            At Lightstorm Telecom Connectivity Private Limited,its subsidiaries
            and associates(hereinafter referred to as “Company”, “we”, “us”,
            “our”), privacy issues are of high priority. We are committed to
            protecting the privacy of our Website visitors,customers, employees
            or agents. This Privacy Policy tells you how the Company will
            collect, use, disclose, transfer, and store your information. Please
            read the Privacy Policy carefully before submitting your information
            and personal data to the Company. By accessing or using our Website,
            you are accepting the practices described in the Privacy Policy and
            acknowledge that you have read, understand, and agree to be bound to
            all the terms of this Privacy Policy.
            <br />
            <br />
            The Privacy Policy may be changed at any time upon the sole
            discretion of the Company and without prior notice to you. The
            revised Privacy Policy will be effective immediately when
            posted/published on our Website. It is your responsibility to review
            the Privacy Policy periodically to learn of any revisions to this
            Privacy Policy. Your continued access oruse of the Website after the
            effectiveness of such revisions will constitute your acknowledgment
            and acceptance of the terms of the revised Privacy Policy.
          </p>
        </div>
        <div>
          <h3>INFORMATION</h3>
          <p>
            We may collect and process the following data or information about
            you.
          </p>
          <ol className=" list-decimal list-inside">
            <li>
              Information you give us about you (Submitted or Personal
              Information)
              <ul className="list-disc list-inside">
                <li>Name</li>
                <li>Address</li>
                <li>Telephone/Mobile number</li>
                <li>E-mail address or other contact information,</li>
                <li>Date of birth,</li>
                <li>Gender</li>
                <li>
                  Any other information which you voluntarily choose to provide
                  to us
                </li>
              </ul>
            </li>
            <li>
              Information provided by you while corresponding with us
              (Non-personal Information)
              <br />
              <br />
              The Company may also collect information other than Personal
              Information from you when you visit our Website or in the course
              of providing services to you or to someone who has provided you
              with access to our services. Such information may be stored on our
              server. This Non-Personal Information may include:
              <ul className="list-disc list-inside">
                <li>
                  Your IP address or your device's location and time zone
                  setting,
                </li>
                <li>
                  Details of your telecom service provider or internet service
                  provider,
                </li>
                <li>
                  The type of browser which you use (Internet Explorer, Firefox,
                  Opera, Google Chrome etc.),
                </li>
                <li>
                  Technical information, including the type of mobile device you
                  use, unique device identifiers (for example, your device's
                  IMEI or serial number), information about the SIM card used by
                  the device, mobile network information, network performance
                  and usage, your device operating system, (Device Information);
                </li>
                <li>
                  Billing Information related to your commercial and financial
                  relationship with us, such as the services we provide to you,
                  the telephone numbers you call and text, your payment history,
                  your credit history, your credit card numbers, social security
                  number(where permitted by law), security codes and your
                  service history. Information we receive from other sources
                  (Third Party Information). We reserve the right to work with a
                  limited number of third parties (including credit reference
                  agencies, mobile network providers, and collection agencies)
                  and may receive information about you from them.
                </li>
              </ul>
            </li>
          </ol>
        </div>
        <div>
          <h3>Collection of Personal Information</h3>
          <p>
            We will only use the information we collect about you lawfully and
            in accordance with the Information Technology Act, 2000, the
            Information Technology (Reasonable security practices and procedures
            and sensitive personal data or information) Rules, 2011 and other
            applicable laws of India. We may collect your personally
            identifiable information such as name, postal address, e-mail
            address and phone number, the device's phone number, SIM card, age,
            username, password and other registration information, financial and
            credit information, personal description, photograph names, credit
            or debit card information and other payment instrument details etc.
            which you voluntarily provide to us for facilitating the services
            provided by the Company. Depending on the activity, some of the
            information we ask you to provide is identified as mandatory and
            some is identified as voluntary. If you do not provide the mandatory
            information for a particular activity, you will not be permitted to
            engage in that activity. You are not required to provide the
            personal information that we have requested, but, if you chose not
            to do so, in many cases we may not be able to provide you with our
            services or respond to any queries you may have. Company and its
            subsidiaries or affiliates may share this personal information with
            each other and/or with the third party and use it consistent with
            this Privacy Policy. They may also combine it with other information
            to provide and improve our services, content, and advertising.
          </p>
          <p>
            We use personally identifiable information to provide services to
            you, fulfil obligations under the contract, response to your
            queries, administer, monitor, improve and customize our Website and
            services, enhance the operation of the Company, improve our
            marketing and promotional efforts, improve our service offerings and
            to tailor your experience with third parties of this Privacy Policy.
            For example, if you send our customer service an email, we may use
            your comments and feedback to tell others about our services and may
            post your comment in our marketing materials or on our Website. In
            addition, if you access or use our Website to send information to
            another person, we may store your personal information, and the
            personal information of any recipient and we may use that other
            person’s contact information to allow him or her to access/view such
            information. We may also use personally identifiable information to
            troubleshoot, resolve disputes, accomplish administrative tasks,
            contact you, enforce our agreements with you, including the
            Company’s Terms of Use located at URL: _______________________ and
            this Privacy Policy, to comply with applicable law, and cooperate
            with law enforcement activities.
          </p>
          <p>
            We also use personally identifiable informationto notify you about
            our new product releases and service development, alerts, events,
            updates prices, terms, special offers and associated campaigns and
            promotions andmake our services and communications more relevant to
            you.
          </p>
          <p>
            We also collect from our users non-personally identifiable
            information. This information does not identify a specific user. We,
            and/or our authorised third-party service providers and advertisers,
            may automatically collect this information when you visit the
            Website through the use of electronic tools like cookies and web
            beacons or pixel tags.
          </p>
          <p>
            We use non-personally identifiable information to troubleshoot,
            administer, analyze trends, gather demographic information, comply
            with applicable law, and cooperate with law enforcement activities.
            We may also share this information with our authorized third-party
            service providers and advertisers to measure the overall
            effectiveness of our advertising, content, and programming.
          </p>
        </div>
        <div>
          <h3>PROTECTION</h3>
          <p>
            We use standard industry practices to protect your information and
            to prevent unauthorized access to your data. Examples of our
            security practices include:
          </p>
          <ol>
            <li>
              Sensitive user data, such as account passwords and email
              addresses, are stored in encrypted format.
            </li>
            <li>
              communications through our Website are sent over SSL/TLS
              connections. Secure Sockets Layer (SSL) and Transport Layer
              Security (TLS) technology protect communications by using both
              server authentication and data encryption. This ensures that user
              data in transit is safe, secure, and available only to intended
              recipients.
            </li>
            <li>
              Automatic applications and infrastructure are regularly tested for
              security vulnerabilities and hardened to enhance security and
              protect against attacks.
            </li>
            <li>
              User data on our database is logically segregated by account-based
              access rules. user accounts have unique usernames and passwords
              that must be entered each time a user logs on.
            </li>
          </ol>
          <p>
            We are committed to handle your personal data or information with
            respect and care. However, regardless of the security precautions
            taken, no physical, Internet or other electronic transmission or
            storage of data can be fully secure or error free. We recommend that
            you do not share your password with anyone. You should understand
            this when choosing to use our services that include the physical or
            electronic storage or transmission of your data.
          </p>
        </div>
        <div>
          <h3>DISCLOSURE OF INFORMATION</h3>
          <p>
            To ensure the security of your personal data or information, we
            always adhere to the principle of data minimization, and share,
            transfer, or disclose your personal data or information in
            accordance with applicable laws and regulations of India.
          </p>
          <p>
            We may share your personal data or information with other parties.
          </p>
          <p>
            We may share your personal data or information inside Company if
            necessary, so that we can provide you with services in a timely
            manner.
          </p>
          <p>
            We may share necessary personal data or information with our
            subsidiaries or affiliates or business partners in accordance with
            the applicable laws and regulations, so that we can provide you with
            the related services.
          </p>
          <p>
            We may share your personal data and information to assist us in
            advertising our products and services in various mediums including
            sending out administrative and promotional emails to you, provide
            marketing assistance, social media platforms, direct mail and by
            telemarketing and may also provide customer service.
          </p>
          <p>
            We may also share your information withauthorised Third-Party
            Service Providers. We may also provide some of our services through
            third party service providers. We may share your personal data or
            informationwith such service providers. Such authorised service
            providers may send out administrative and promotional emails to you,
            provide marketing assistance, articles/news and links, process
            payments, troubleshoot, and may also provide customer service. We
            encourage such third-party service providers to adopt and post
            privacy policies. However, the use of your personal data or
            information by such parties is governed by the privacy policies of
            such parties and is not subject to our control.
          </p>

          <p>
            We may share your information for our Protection and the Protection
            of Others. We may also disclose personal data or information when we
            believe release is appropriate to comply with the law or a court
            order; enforce or apply this Privacy Policy, our Terms of Use or
            other agreements; or protect the rights, property or safety of the
            Company, its subsidiaries, affiliates or others. The Company may
            also disclose account information in special casesif it has reasons
            to believe that disclosing this information is necessary to
            identify, contact or bring legal action against someone who may be
            violating Company's Terms of Use or may be causing injury to or
            interference with (either intentionally or unintentionally) Company
            's rights or property.
          </p>
        </div>
        <div>
          <h3>Other Disclosure</h3>
          <p>
            We may disclose your personal data or information to any member of
            our group, which means our subsidiaries, our ultimate holding
            company and its subsidiaries.
          </p>
          <p>
            We may disclose your personal data or information to third parties:
          </p>
          <li>
            In the event that we are acquired by or merge with another company
            orwe sell or buy or transferred any business or assets to another
            company, in which case Company may disclose your personal data or
            information to the prospective seller or buyer or transferee of such
            business or assets;
          </li>
          <li>
            If the Company or substantially all of its assets are acquired by a
            third party, in which case personal data or information held by it
            about its users/customers will be one of the transferred assets;
          </li>
          <li>If you authorize said disclosure;</li>
          To facilitate your access to the Website;
          <li>
            In order to enforce our Terms of Use and other agreements or to
            investigate potential breaches; report defaulters to any bureau or
            agency; engage a third party collections agency; or for the purpose
            of publishing statistics relating to the use of the Website, in
            which case all information will be aggregated and made anonymous
          </li>
          <li>
            To respond to your inquiries or fulfil your requests for information
            about the various services offered on the Website;
          </li>
          <li>
            To send you important information regarding our products or
            services, changes in terms and conditions, user agreements, and
            policies and/or other administrative information;
          </li>
          <li>
            To help you address your problems including addressing any technical
            problems;
          </li>
          <li>
            To improve the services, content and advertising on the Website;
          </li>
          <li>
            To protect the integrity of the Company as well as of Company’s
            Website and Intellectual Property Rights;
          </li>
          <li>
            To respond to legal, judicial, quasi-judicial process and provide
            information to law enforcement agencies or in connection with an
            investigation on matters related to public safety, as permitted by
            law;
          </li>
          <li>To implement information security practices;</li>
          <li>
            To determine any security breaches, computer contaminant or computer
            virus;
          </li>
          <li>
            To investigate, prevent, or take action regarding illegal activities
            and suspected fraud,
          </li>
          <li>
            To undertake forensics of the concerned computer resource as a part
            of investigation or internal audit;
          </li>
          <li>
            To trace computer resources or any person who may have contravened,
            or is suspected of having or being likely to contravene, any
            provision of law including the Information Technology Act, 2000 that
            is likely to have an adverse impact on the services provided on the
            Website.
          </li>
        </div>
        <div>
          <h3>RELEASE OF NON-PERSONALLY IDENTIFIABLE INFORMATION</h3>
          <p>
            We may use your data for the purposes of compiling statistics
            relating to our user base or user portfolio and may disclose such
            information to any third party for such purposes, provided that such
            information is used anonymously.
          </p>

          <p>
            We may disclose or share non-personally identifiable information
            with partners, affiliates and advertisers. For example, we may share
            aggregated demographic information (which does not include any
            personally identifiable information) with “third party advertisers”
            or “third party advertising companies” and other parties.
          </p>
          <p>
            We may use third party advertising companies to serve ads when you
            access our Website. These companies may use non-personally
            identifiable information about your visits to this and other
            websites in order to provide, through the use of network tags,
            advertisements about goods and services that may be of interest to
            you.
          </p>
          <p>
            We may also use third party service providers to track and analyze
            non-personally identifiable usage and volume statistical information
            from our users to administer our services and constantly improve its
            quality. We may also publish this information for promotional
            purposes or as a representative audience for advertisers. Please
            note that this is not personally identifiable information, only
            general summaries of the activities of our users.
          </p>
        </div>
        <div>
          <h3>User Discretion and Opt-Out</h3>
          <ol>
            <li>
              You agree and acknowledge that you are providing your information
              out of your free will and consent. You may opt-out of receiving
              further communication from the Company. To withdraw / be
              completely removed from any updates, you may send an email to the
              grievance officer.
            </li>
            <li>
              You can add or update your personal information on regular basis.
              Kindly note that Company would retain your previous personal
              information in its records for a minimum period of 3 years fromm
              the date of submission.
            </li>
          </ol>
        </div>
        <div>
          <h3>DATA TRACKING</h3>
          <p>
            Cookies: To facilitate and customize your experience with the
            Website, we may store cookies on your electronic devices. A cookie
            is a small text file that is stored on a user’s electronic device
            for record-keeping purposes which contains information about that
            user. We use cookies to save your time while accessing and using the
            Website, remind us who you are, and track and target your interests
            in order to provide a customized experience. Cookies also allow us
            to collect non-personally identifiable information from you, like
            which pages you visited and what links you clicked on. Use of this
            information helps us to create a more user-friendly experience for
            all visitors. In addition, we may use third party advertising
            companies to display advertisements on our Website. As part of their
            service, they may place separate cookies on your electronic device.
            We have no access to or control over these cookies. This Privacy
            Policy covers the use of cookies by our Website only and does not
            cover the use of cookies by any advertiser. Most browsers
            automatically accept cookies, but you may be able to modify your
            browser settings to decline cookies. Please note that if you decline
            or delete these cookies, some parts of our Website may not work
            properly.
          </p>
        </div>
        <div>
          <h3>Session Data</h3>
          <p>
            We may automatically log generic information about your device's
            connection to the Internet, which we call "session data", that is
            anonymous and not linked to any personal information. Session data
            consists of information such as the IP address, operating system,
            type of browser software being used by you and the activities
            conducted by you on our Website. An IP address is a number that lets
            electronic device attached to the Internet, such as our web servers,
            know where to send data back to the user, such as the pages of the
            site the user wishes to view. We collect session data because it
            helps us analyze things such as the items visitors are likely to
            click on most, the manner in which visitors click preferences on our
            Website, number of visitors surfing to various pages on our Website,
            time spent by the visitors on the Website and frequency of their
            visit. It also helps us diagnose problems with our servers and lets
            us better administer our systems. Although such information does not
            identify any visitor personally, it is possible to determine from an
            IP address a visitor's Internet Service Provider (ISP), and the
            approximate geographic location of his or her point of connectivity.
          </p>
          <p>
            Tracking Devices: We may use other industry standard technologies
            like pixel tags and web beacons to track your access and use of our
            Website pages and promotions, or we may allow our third-party
            service providers to use these devices on our behalf. Pixel tags and
            web beacons are tiny graphic images placed on certain pages on our
            Website, or in our emails that allow us to determine whether you
            have performed a specific action. When you access these pages or
            open or click an email, pixel tags and web beacons generate a
            non-personally identifiable notice of that action. Pixel tags allow
            us to measure and improve our understanding of visitor traffic and
            behavior on our Website, as well as give us a way to measure our
            promotions and performance. We may also utilize pixel tags and web
            beacons provided by our affiliates and/or marketing partners for the
            same purposes.
          </p>
        </div>
        <div>
          <h3>PRIVACY POLICIES OF THIRD-PARTY PLATFORMS</h3>
          <p>
            This Privacy Policy only addresses the use and disclosure of
            information we collect from you. Other websites that may be
            accessible through this Website have their own privacy policies and
            data collection, use and disclosure practices. If you link to any
            such website, we urge you review the website’s privacy policy. We
            are not responsible for the policies or practices of third parties.
          </p>
        </div>
        <div>
          <h3>MISCELLANEOUS PRIVACY ISSUES</h3>
          <p>
            Force Majeure: Company shall not be liable for its failure to
            perform under this Privacy Policy and any other Company’s policies
            as a result of occurrence of any force majeure events like acts of
            God, fire, wars, sabotage, civil unrest, labour unrest, pandemic,
            epidemic, action of statutory authorities or local or central
            governments, change in laws, rules and regulations, affecting the
            performance of Company. Amendment: This Privacy Policy may be
            amended from time to time so please check periodically. The revised
            document shall be made available on this Website. Your continued
            access and use of Website, following amendment to the document, will
            constitute your acceptance of those amendments. Governing Law &
            Jurisdiction: Any disputes arising under this document shall be
            governed by the laws of India and subject to the exclusive
            jurisdiction of the courts at New Delhi, India only. Report
            Violation: You should report any security violations that come to
            your notice at the earliest to us by sending an email to
            enquiry@lightstormtelecom.com
          </p>
        </div>
        <div>
          <h3>CONTACTING US</h3>
          <p>For any further queries please contact us at:</p>
          <p>Grievance Officer:</p>
          <a href="mailto:enquiry@lightstormtelecom.com">
            Email: enquiry@lightstormtelecom.com
          </a>
        </div>
      </div>
  );
};

export default PrivacyPolicy;
