const TermsConditions = () => {
  return (
    <div
      className="text-white/70 space-y-4 md:space-y-8 [&_div]:space-y-4 [&_h3]:text-white [&_h3]:font-semibold"
    >
      <div id="div_block-581-2042" className="ct-div-block">
        <h3 id="headline-582-2042" className="ct-headline">
          THIS DOCUMENT IS AN ELECTRONIC RECORD PUBLISHED IN ACCORDANCE WITH THE
          PROVISIONS OF THE INFORMATION TECHNOLOGY ACT, 2000 AND RULES
          THEREUNDER AS APPLICABLE AND THE AMENDED PROVISIONS PERTAINING TO
          ELECTRONIC RECORDS IN VARIOUS STATUTES. THIS ELECTRONIC RECORD IS
          GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR
          DIGITAL SIGNATURES.
        </h3>
        <div id="text_block-583-2042" className="ct-text-block">
          Please read the following terms of use carefully before accessing or
          using any information or availing any services of the Company through
          its online platform i.e., https://polarin.lightstorm.net. (hereinafter
          collectively referred to as the “Website”). By accessing/using the
          Website or by clicking the “I Agree” button will constitute a symbol
          of your signature, you acknowledge and admit that you have fully read,
          understood the terms and you expressly and unconditionally agree to
          the terms and all other policies of the Company including but not
          limited to, Privacy Policy. If you do not agree with any part of these
          Terms of Use and Privacy Policy as set out herein below, please
          refrain from assessing/using the Website.
        </div>
      </div>
      <div id="div_block-584-2042" className="ct-div-block">
        <h3 id="headline-585-2042" className="ct-headline">
          General Conditions
        </h3>
        <div id="text_block-586-2042" className="ct-text-block">
          The Website by the domain name https://polarin.lightstorm.net. is
          owned and operated by Lightstorm Data Centers Private Limited, a
          company duly registered under the provisions of the Indian Companies
          Act, 2013 having its registered office at Office No. 118 , FF,
          Vardhman Plaza, Tower BLK-H-3, Netaji Subhash Place, Pitampura, New
          Delhi 110034 (hereinafter referred to as the “Company”). These Terms
          of Use together with Privacy Policy located at URL:
          <u> https://polarin.lightstorm.net/privacy-policy/ </u>and any other
          terms &amp; conditions which may apply to any other specific services
          together with all other notices, disclaimers, guidelines (collectively
          referred to as “Terms of Use”) provided on the Website from time to
          time, constitutes a legally enforceable contract between you as an
          individual (assuming you are above 18 years and/or eligible to enter
          into an agreement), or the company or any legal entity/organization
          that will be using the services of the Company (hereinafter referred
          to as 'you' or 'your') and the Company. You shall have the right to
          use the Website subject to the terms and conditions mentioned in this
          agreement or as amended by the Company from time to time. The term
          "we", "us", "our" shall mean the Company and the term "you”, "your",
          "user", "member" shall mean User(s).
        </div>
      </div>
      <div id="div_block-587-2042" className="ct-div-block">
        <h3 id="headline-588-2042" className="ct-headline">
          Description of Services
        </h3>
        <div id="text_block-589-2042" className="ct-text-block">
          The Website contains the important and detailed information regarding
          Company’s business. The Company is into the business of providing
          network as a services (NaaS) online platform providing cloud
          connectivity services including connectivity from clouds to
          datacenters and vice versa and other services integrated therein.{" "}
          <br />
          <br />
          You expressly agree that the use of the Website is at your sole risk.
          Any data, information, third-party software, content (including
          commercial content), reference sites, services, or applications made
          available in conjunction with or through the Website are provided on
          an "as is" and "as available", "with all faults" basis and without
          warranties or representations of any kind either express or implied.
          <br />
          <br />
          Company reserves the right at all times to discontinue or modify
          Content of the Website, terms and conditions and/or the Privacy Policy
          as may be deemed necessary or desirable without prior notification to
          you. The features/information on the Website may be permanently
          deleted, temporarily removed and/or added as and when new
          versions/updates are released. It shall be your responsibility for
          regularly reviewing these Terms of Use. If Company makes changes to
          these Terms of Use as set out in this agreement or its Privacy Policy
          and you continue to use the Website, you are impliedly agreeing to the
          agreement and Privacy Policy expressed herein. Any such deletions or
          modifications to the terms and conditions of the agreement and/or
          Privacy Policy shall be effective immediately upon Company's posting
          thereof on the Website. Any use of Website by you after such notice
          shall be deemed to constitute acceptance by you of such modifications
          and/or changes.
        </div>
      </div>
      <div id="div_block-590-2042" className="ct-div-block">
        <h3 id="headline-591-2042" className="ct-headline">
          Intellectual Property Rights
        </h3>
        <div id="text_block-592-2042" className="ct-text-block">
          All information, content, services and software displayed on,
          transmitted through, or used in connection with the Website, including
          for example text, photographs, images, illustrations, audio clips,
          video, html, source and object code, trademarks, logos, and the like
          (collectively and hereinafter referred to as the “Content”), as well
          as its selection and arrangement, is owned by us. You may use the
          Company’s Content only through Website, and solely for your personal,
          non-commercial use.
          <br />
          <br />
          You shall not use the name, logo, or any trade name or trademark,
          design, Content or copyright of the Company without prior written
          consent of the Company. The marks representing the intellectual
          property rights of the Company including trademarks, copyrights,
          designs, colour, schemes, etc., shall at all times vest in/with the
          Company. You shall not claim any right, title, or ownership of any
          nature whatsoever in/over any intellectual property of the Company at
          any time.
          <br />
          <br />
          You shall not, republish any portion of the Content on any Internet,
          Intranet or extranet site or incorporate the Content in any database,
          compilation, archive or cache. You may not distribute any Content to
          others, whether or not for payment or other consideration, and you may
          not modify, copy, frame, cache, reproduce, sell, publish, transmit,
          display or otherwise use any portion of the Content. You may not
          scrape or otherwise copy the Content without permission. You agree not
          to decompile, reverse engineer or disassemble any software or other
          services, products or processes accessible through the Website; not to
          insert any code or product or manipulate the content of the Website in
          any way that affects the user's experience, and not to use any data
          mining, data gathering or extraction method.
        </div>
      </div>
      <div id="div_block-593-2042" className="ct-div-block">
        <h3 id="headline-594-2042" className="ct-headline">
          Third Party Content
        </h3>
        <div id="text_block-595-2042" className="ct-text-block">
          Links to third party website are provided by the Company as a
          convenience to user(s) and Company does not have any control over such
          websites i.e., content and resources provided by them.
          <br />
          <br />
          Company may allow user(s) access to content, products or services
          offered by third parties through hyperlinks (in the form of word link,
          banners, channels or otherwise) to such third party's services. You
          are cautioned to read such websites' terms and conditions and/or
          privacy policies before using such websites to be aware of the terms
          and conditions of your use of such websites. Company believes that
          user(s) acknowledge that Company has no control over such third
          party's website, does not monitor such websites, and Company shall not
          be responsible or liable to anyone for such third party website, or
          any content, products or services made available on such a website.
          <br />
          <br />
          In the event any third party content contains links to third party
          websites, and you visit any such external link, you agree to do so at
          your own risk, responsibility and liability. Company makes no warranty
          or representation regarding, and does not endorse, any website linked
          to Website/services or the information appearing thereon or any of the
          products or services described thereon.
        </div>
      </div>
      <div id="div_block-596-2042" className="ct-div-block">
        <h3 id="headline-597-2042" className="ct-headline">
          Warranties
        </h3>
        <div id="text_block-598-2042" className="ct-text-block">
          You warrant that you will not use the Website/Content in any unlawful
          manner and if you commit any breach of these Terms of Use, Company
          will have the right to immediately suspend or terminate your access or
          use of the Website to prevent harm to the Company or its business and
          to limit any potential liability. Company also reserves the right to
          seek all remedies available by law and in equity for such violations.
          <br />
          <br />
          If practicable, Company will provide notice and opportunity to cure
          any breach. Once cured, in Company's sole discretion, Company will use
          reasonable efforts to restore your access to the Website.
        </div>
      </div>
      <div id="div_block-599-2042" className="ct-div-block">
        <h3 id="headline-600-2042" className="ct-headline">
          Restriction on Usage
        </h3>
        <div id="text_block-601-2042" className="ct-text-block">
          You must not use the Website/Content:
        </div>
        <div id="div_block-602-2042" className="ct-div-block oxel_iconlist">
          <div
            id="div_block-603-2042"
            className="ct-div-block oxel_iconlist__row"
          >
            <div
              id="fancy_icon-604-2042"
              className="ct-fancy-icon oxel_iconlist__row__icon"
            ></div>
            <div
              id="text_block-605-2042"
              className="ct-text-block oxel_iconlist__row__label"
            >
              For fraudulent purposes, or in connection with a criminal offense
              or other unlawful activity;
            </div>
          </div>
          <div
            id="div_block-606-2042"
            className="ct-div-block oxel_iconlist__row"
          >
            <div
              id="fancy_icon-607-2042"
              className="ct-fancy-icon oxel_iconlist__row__icon"
            ></div>
            <div
              id="text_block-608-2042"
              className="ct-text-block oxel_iconlist__row__label"
            >
              For any unlawful purpose (including, without limitation for
              violation of any data, privacy or other applicable laws) or in any
              manner that interferes with or disrupts the integrity or
              performance of the Website;
            </div>
          </div>
          <div
            id="div_block-609-2042"
            className="ct-div-block oxel_iconlist__row"
          >
            <div
              id="fancy_icon-610-2042"
              className="ct-fancy-icon oxel_iconlist__row__icon"
            ></div>
            <div
              id="text_block-611-2042"
              className="ct-text-block oxel_iconlist__row__label"
            >
              For solicitation or any commercial purpose;
            </div>
          </div>
          <div
            id="div_block-612-2042"
            className="ct-div-block oxel_iconlist__row"
          >
            <div
              id="fancy_icon-613-2042"
              className="ct-fancy-icon oxel_iconlist__row__icon"
            ></div>
            <div
              id="text_block-614-2042"
              className="ct-text-block oxel_iconlist__row__label"
            >
              To sell or otherwise distribute confidential information of the
              Company;
            </div>
          </div>
          <div
            id="div_block-615-2042"
            className="ct-div-block oxel_iconlist__row"
          >
            <div
              id="fancy_icon-616-2042"
              className="ct-fancy-icon oxel_iconlist__row__icon"
            ></div>
            <div
              id="text_block-617-2042"
              className="ct-text-block oxel_iconlist__row__label"
            >
              To send, use or reuse any material that does not belong to you; or
              that is libelous, defamatory or unlawful, or violates or infringes
              any trademark, copyright, confidentiality or similar rights of
              others;
            </div>
          </div>
          <div
            id="div_block-618-2042"
            className="ct-div-block oxel_iconlist__row"
          >
            <div
              id="fancy_icon-619-2042"
              className="ct-fancy-icon oxel_iconlist__row__icon"
            ></div>
            <div
              id="text_block-620-2042"
              className="ct-text-block oxel_iconlist__row__label"
            >
              To modify, adapt or hack the Website to, or otherwise attempt to,
              gain unauthorized access to the Website.
            </div>
          </div>
        </div>
        <div id="text_block-621-2042" className="ct-text-block">
          If the Company suspect any illegal, wrongful or fraudulent activity on
          the Website by any user, notwithstanding any other rights which
          Company may have, Company shall inform the relevant government
          authorities to take further action.
          <br />
          <br />
          You are prohibited from probing, testing, or violating the Website's
          security or attempting to do so, including (i) accessing data not
          intended for you or logging into a service or account that you are not
          authorized to access, (ii) attempting to probe, scan, or test the
          vulnerability of a system or network or to breach security or
          authentication measures, and (iii) attempting to interfere with the
          Website's security or authentication measures, host or network
          including, without limitation, via means of submitting a virus or
          malware etc. " or (iv) sending unsolicited electronic mail including,
          promotions and / or advertising of other products or services.
          <br />
          <br />
          Without Company’s prior written authorization, you may not mirror any
          of the Website's content on another server. Any unauthorized use of
          the Website/Content might be a violation of copyright or trademark
          laws.
        </div>
      </div>
      <div id="div_block-622-2042" className="ct-div-block">
        <h3 id="headline-623-2042" className="ct-headline">
          Disclaimer
        </h3>
        <div id="text_block-624-2042" className="ct-text-block">
          THE WEBSITE, CONTENT AND ANY THIRD PARTY CONTENT ARE PROVIDED BY THE
          COMPANY ON AN "AS IS" BASIS WITHOUT WARRANTY OF ANY KIND, EXPRESS,
          IMPLIED, STATUTORY OR OTHERWISE, INCLUDING THE IMPLIED WARRANTIES OF
          TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR
          PURPOSE. WITHOUT LIMITING THE FOREGOING, COMPANY MAKES NO WARRANTY
          THAT (I) WEBSITE OR THE CONTENT WILL MEET YOUR REQUIREMENTS OR YOUR
          USE OF WEBSITE OR THE CONTENT WILL BE UNINTERRUPTED, TIMELY, SECURE OR
          ERROR-FREE; (II) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF
          WEBSITE OR CONTENT WILL BE EFFECTIVE, ACCURATE OR RELIABLE; (III) THE
          QUALITY OF WEBSITE OR CONTENT WILL MEET YOUR EXPECTATIONS; OR THAT
          (IV) ANY ERRORS OR DEFECTS IN WEBSITE OR CONTENT WILL BE CORRECTED. NO
          ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM
          COMPANY OR THROUGH WEBSITE OR FROM USE OF THE CONTENT SHALL CREATE ANY
          WARRANTY NOT EXPRESSLY STATED IN THESE TERMS OF USE.
          <br />
          <br />
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, COMPANY WILL HAVE
          NO LIABILITY RELATED TO USER INFORMATION/CONTENT AND/OR THIRD-PARTY
          CONTENT ARISING UNDER INTELLECTUAL PROPERTY RIGHTS, LIBEL, PRIVACY,
          PUBLICITY, OBSCENITY OR OTHER LAWS. COMPANY ALSO DISCLAIMS ALL
          LIABILITY WITH RESPECT TO THE MISUSE, LOSS, MODIFICATION OR
          UNAVAILABILITY OF ANY USER INFORMATION/CONTENT AND/OR THIRD-PARTY
          CONTENT.
          <br />
          <br />
          YOU EXPRESSLY UNDERSTAND AND AGREE THAT, TO THE MAXIMUM EXTENT
          PERMITTED BY APPLICABLE LAW COMPANY WILL NOT BE LIABLE FOR ANY
          PUNITIVE, DIRECT, INDIRECT, SPECIAL, INCIDENTAL, EXEMPLARY OR
          CONSEQUENTIAL DAMAGES OR LOSS THAT YOU MAY INCUR AS A CONSEQUENCE OF
          UNAUTHORIZED USE OF THE WEBSITE OR ANY CONTENT, EITHER WITH OR WITHOUT
          YOUR KNOWLEDGE. COMPANY HAS ENDEAVOURED TO ENSURE THAT ALL THE
          INFORMATION ON THE WEBSITE IS CORRECT, BUT COMPANY NEITHER WARRANTS
          NOR MAKES ANY REPRESENTATIONS REGARDING THE QUALITY, ACCURACY OR
          COMPLETENESS OF ANY DATA, INFORMATION, PRODUCT OR SERVICE. COMPANY
          SHALL NOT BE RESPONSIBLE FOR THE DELAY OR INABILITY TO ACCESS OR USE
          WEBSITE OR RELATED FUNCTIONALITIES, THE PROVISION OF OR FAILURE TO
          PROVIDE SERVICES, OR FOR ANY INFORMATION, SOFTWARE, PRODUCTS,
          FUNCTIONALITIES AND RELATED GRAPHICS OBTAINED THROUGH WEBSITE, OR
          OTHERWISE ARISING OUT OF THE ACCESS OR USE OF WEBSITE, WHETHER BASED
          ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE. FURTHER,
          COMPANY SHALL NOT BE HELD RESPONSIBLE FOR NON-AVAILABILITY OF WEBSITE
          OR CONTENT DURING PERIODIC MAINTENANCE OPERATIONS OR ANY UNPLANNED
          SUSPENSION OF ACCESS TO THE WEBSITE THAT MAY OCCUR DUE TO TECHNICAL
          REASONS OR FOR ANY REASON BEYOND COMPANY'S CONTROL. THE USER
          UNDERSTANDS AND AGREES THAT ANY MATERIAL OR DATA DOWNLOADED OR
          OTHERWISE OBTAINED THROUGH WEBSITE IS DONE ENTIRELY AT THEIR OWN
          DISCRETION AND RISK AND THEY WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE
          TO THEIR MOBILE PHONES OR COMPUTER SYSTEMS OR ELECTRONIC DEVICES OR
          LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL OR DATA.
          COMPANY ACCEPTS NO LIABILITY FOR ANY ERRORS OR OMISSIONS, WITH RESPECT
          TO ANY INFORMATION PROVIDED TO YOU WHETHER ON BEHALF OF ITSELF OR
          THIRD PARTIES.
        </div>
      </div>
      <div id="div_block-625-2042" className="ct-div-block">
        <h3 id="headline-626-2042" className="ct-headline">
          Limited Liability
        </h3>
        <div id="text_block-627-2042" className="ct-text-block">
          You expressly understand and agree that the Company and its
          subsidiaries, affiliates, officers, employees, agents, partners and
          licensors shall not be liable to you for any direct, indirect,
          incidental, special, consequential or exemplary damages, including,
          but not limited to, damages for loss of profits, opportunity,
          goodwill, use, data or other intangible losses (even if the Company
          has been advised of the possibility of such damages), resulting from
          access or use of the Website, Content and other services/products
          offered by the Company from time to time.
          <br />
          <br />
          You acknowledge that Company relies on third party internet services
          providers and at times, actions or omissions of such third parties can
          impair or disrupt your connections to the internet or have an adverse
          effect on the Content provided at the Website or parts thereof and may
          result in presenting inaccurate data on the Website. Although Company
          will use commercially reasonable efforts to take actions it deems
          appropriate to remedy and avoid such events with respect to your
          access or use of the Website, however, Company cannot guarantee that
          such events will not occur. Accordingly, Company excludes any and all
          liability resulting from, or related to, such events. The Website is
          available solely on an "as is" and “as available” basis, and your
          access or use of Website is at your own risk. Company does not warrant
          that Website will be uninterrupted, error-free, or completely secure.
          The Content may have typographical errors.
          <br />
          <br />
          Website/Content should not be construed under any circumstances to be
          an opinion or advice but is only provided to assist you. If you rely
          on any of the information provided by the Company on its Website, you
          do so solely at your own risk. The information that you obtain or
          receive from the Website or otherwise is for informational purposes
          only. In no event shall Company be liable to you or anyone else for
          any decision made or action taken by you in reliance on such
          information.
        </div>
      </div>
      <div id="div_block-628-2042" className="ct-div-block">
        <h3 id="headline-629-2042" className="ct-headline">
          Indemnity
        </h3>
        <div id="text_block-630-2042" className="ct-text-block">
          You agree to indemnify, defend and hold harmless Company, its
          subsidiaries, affiliates, vendors, agents and their respective
          directors, officers, employees, contractors and agents (herein after
          individually and collectively referred to as "indemnified parties")
          from and against any and all losses, liabilities, claims, suits,
          proceedings, penalties, interests, damages, demands, costs and
          expenses (including legal and other statutory fees and disbursements
          in connection therewith and interest chargeable thereon) asserted
          against or incurred by the indemnified parties that arise out of,
          result from, or in connection with (i) your breach of the Terms of
          Use/agreement(s); or (ii) any claims made by any third party due to,
          or arising out of, or in connection with, your access or use of
          Website; or (iii) your breach of Company’s intellectual property
          rights ; or (iv) your violation of any rights of another, including
          any intellectual property rights.
          <br />
          <br />
          The Company may notify you of any claims which you shall be liable to
          indemnify Company against. You will then be required to consult with
          Company regarding the course of action to be undertaken in defending
          such a claim. Further, you shall not compromise or settle any claim or
          admit any liability or wrongdoing on the part of Company without the
          express prior written consent of Company which can be withheld or
          denied or conditioned by Company in its sole discretion.
          <br />
          <br />
          Notwithstanding anything to contrary in the Terms of Use, Company's
          entire and aggregate liability to you under and in relation to these
          Terms of Use or otherwise shall not exceed the amount of fees paid by
          you to Company for the individual or that part of transaction that is
          the subject of the claim or Indian Rupees One Thousand Only (INR
          1000/-), whichever is less.
        </div>
      </div>
      <div id="div_block-631-2042" className="ct-div-block">
        <h3 id="headline-632-2042" className="ct-headline">
          Confidential Information
        </h3>
        <div id="text_block-633-2042" className="ct-text-block">
          Any information or material as provided by you to the Company will not
          be deemed as confidential information and by providing any information
          or material to the Company, you grant Company an unrestricted and
          unlimited, a worldwide, non-exclusive, perpetual, irrevocable,
          royalty-free, fully paid, sub-licensable and transferable license to
          use, modify, reproduce, distribute, display, publish and perform your
          details/information. You hereby also agree and undertake to allow the
          Company to freely use any ideas, concepts, know-how, plans, or
          techniques that you send or share with the Company, for any purpose
          whatsoever. The Company shall not release your name or otherwise
          publicize the fact that you submitted materials or other information
          to the Company unless: (a) the Company obtain your permission to use
          your name; or (b) first notify you that the materials or other
          information you submit to a particular part of this Website or
          otherwise used with your name on it; or (c) the Company is required to
          do so by law.
          <br />
          <br />
          Personally Identifiable Information that you submit to the Company for
          the purpose of receiving any products or services from the Company,
          will be handled in accordance with our Privacy Policy.
        </div>
      </div>
      <div id="div_block-634-2042" className="ct-div-block">
        <h3 id="headline-635-2042" className="ct-headline">
          Applicable Law
        </h3>
        <div id="text_block-636-2042" className="ct-text-block">
          Any contract or non-contractual dispute or claim arising out of or in
          connection with these Terms of Use and the relationship between you
          and Company shall be governed in accordance with the laws of India
          without reference to conflict of laws principles. You agree that all
          claims, differences and disputes arising under or in connection with
          or in relation hereto to your access or use of the Website, these
          Terms of Use or the relationship between you and Company shall be
          subject to the exclusive jurisdiction of the courts at New Delhi,
          India and you hereby accede to and accept the jurisdiction of such
          courts. Each party hereby irrevocably waives any objection which such
          party may now or hereafter have to the laying of improper venue or
          forum non convenient. Each party agrees that a judgment in any such
          action or proceeding may be enforced in other jurisdictions by suit on
          the judgment or in any manner provided by law. Any and all service of
          process and any other notice in any such suit, action or proceeding
          with respect to these Terms of Use shall be effective against a party
          if given as provided herein.
        </div>
      </div>
      <div id="div_block-637-2042" className="ct-div-block">
        <h3 id="headline-638-2042" className="ct-headline">
          Severability
        </h3>
        <div id="text_block-639-2042" className="ct-text-block">
          If any of the terms under these Terms of Use is deemed to be illegal,
          invalid or otherwise unenforceable by reason of the laws of any state
          in which these terms and conditions are intended to be effective, then
          to the extent and within the jurisdiction where that term is illegal,
          invalid or unenforceable, it shall be severed and deleted and the
          remaining terms and conditions shall survive, remain in full force and
          effect and continue to be binding and enforceable.
        </div>
      </div>
      <div id="div_block-640-2042" className="ct-div-block">
        <h3 id="headline-641-2042" className="ct-headline">
          Survival
        </h3>
        <div id="text_block-642-2042" className="ct-text-block">
          All of the terms and conditions including, Confidentiality,
          Intellectual Property Rights, disclaimer and warranties, limitation of
          liability, covenants and representations of the respective Parties
          hereto shall survive the termination or expiration of any relationship
          between the Company and you shall continue in full force and effect
          thereafter.
        </div>
      </div>
      <div id="div_block-643-2042" className="ct-div-block">
        <h3 id="headline-644-2042" className="ct-headline">
          Notices
        </h3>
        <div id="text_block-645-2042" className="ct-text-block">
          All of the terms and conditions including, Confidentiality,
          Intellectual Property Rights, disclaimer and warranties, limitation of
          liability, covenants and representations of the respective Parties
          hereto shall survive the termination or expiration of any relationship
          between the Company and you shall continue in full force and effect
          thereafter.
        </div>
      </div>
      <div id="div_block-646-2042" className="ct-div-block">
        <h3 id="headline-647-2042" className="ct-headline">
          Entire Agreement
        </h3>
        <div id="text_block-648-2042" className="ct-text-block">
          These Terms of Use constitutes the entire agreement between you and
          the Company and governs your access or use of Website, superseding any
          prior agreements or terms of service on the same subject matter,
          between you and the Company.
        </div>
      </div>
      <div id="div_block-649-2042" className="ct-div-block">
        <h3 id="headline-650-2042" className="ct-headline">
          Suspension or Modifications of Terms of Use
        </h3>
        <div id="text_block-651-2042" className="ct-text-block">
          You acknowledge and agree that the Company may, at any time and
          without notice, suspend or change the entire Website or any portion of
          it for any reason whatsoever. The Company retains the right to make
          further modifications to the Website or Content and services, as
          needed, in light of business exigencies and/or TRAI, Department of
          Telecom (DOT) and/or statutory changes, and the same shall be binding
          on you. Such changes, modifications, and additions shall be deemed
          effective and in force as soon as the new terms are posted on the
          Website. You should thus check this Website on a frequent basis for
          any updates or amendments to these Terms of Use, and if the updated or
          amended terms and conditions are unacceptable to you, then you should
          stop using the Website.
        </div>
      </div>
      <div id="div_block-652-2042" className="ct-div-block">
        <h3 id="headline-653-2042" className="ct-headline">
          Force Majeure
        </h3>
        <div id="text_block-654-2042" className="ct-text-block">
          The Company shall not be liable for its failure to perform under these
          Terms of Use as a result of occurrence of any force majeure events
          like acts of God, fire, wars, sabotage, civil unrest, labour unrest,
          pandemic, epidemic, economic slowdown, action of statutory authorities
          or local or central governments, change in laws, rules and
          regulations, affecting the performance of Company.
        </div>
      </div>
      <div id="div_block-655-2042" className="ct-div-block">
        <h3 id="headline-656-2042" className="ct-headline">
          Miscellaneous
        </h3>
        <div id="text_block-657-2042" className="ct-text-block">
          (a) It is agreed and clarified that the arrangement set out by these
          Terms of Use and other Company policies between Company and the
          User(s) is on a non-exclusive basis.
          <br />
          <br />
          (b) Use of Website is available only to persons who can form a legally
          binding contract under the Indian Contract Act, 1872. If you are a
          minor i.e., under the age of 18 years, you may use Website only with
          supervision/involvement of a parent or guardian.
          <br />
          <br />
          (c) In no circumstances, the Company shall be liable for any damages
          to, or viruses that may infect, your computer, any electronic
          equipment or other property on account of your access or use of the
          Website or your downloading of any materials, data, text, or images
          from this Website.
          <br />
          <br />
          (d) The failure of the Company to exercise or enforce any right or
          provision of these Terms of Use with respect to a breach by you or
          others does not waive its right to act with respect to subsequent or
          similar breaches.
          <br />
          <br />
          (e) Third party shall have no rights to enforce any terms contained
          herein.
          <br />
          <br />
          (f) The Company for your convenience may provide translated version of
          these terms and conditions in different language. To the extent any
          translated version of these terms and conditions conflicts with this
          English version, this English version shall prevail.
          <br />
          <br />
          (g) Except as otherwise, expressly provided in these Terms of Use,
          there shall be no third-party beneficiaries to these Terms of Use or
          license provided hereunder. You acknowledge that these Terms of Use is
          a contract between you and us, even though it is electronic and is not
          physically signed by you and the Company, and it governs your access
          or use of Website.
        </div>
      </div>
      <div id="div_block-658-2042" className="ct-div-block">
        <h3 id="headline-659-2042" className="ct-headline">
          Contact Us
        </h3>
        <div id="text_block-660-2042" className="ct-text-block">
          Any questions or comments regarding the Website or its content, please
          write to us at&nbsp;enquiry@lightstormtelecom.com
        </div>
      </div>
      <div id="div_block-662-2042" className="ct-div-block">
        <h3 id="headline-663-2042" className="ct-headline">
          Grievance Officer
        </h3>
        <div id="text_block-664-2042" className="ct-text-block">
          For any complaints or queries, please contact our Grievance Officer at
          enquiry@lightstormtelecom.com, who is duly appointed in accordance
          with Information Technology Act, 2000 and rules made there
          under.&nbsp;
        </div>
      </div>
    </div>
  );
};

export default TermsConditions;
